### ISSUE TITLE
DTLoadingTemplate.compileHtml is not a function at Object.showLoading

### ISSUE THREAD

**Issue by rjalvesp** [l-lin/angular-datatables#609]
Hi guys, and hi l-lin, I hope everybody is having fun (or stressing, choose the one that give you dopamine).

I was working with 0.4.x version until I needed to make server-side pagination and needed to enable some withColumnFilter, but it turns out that cheking angular-datatables's page I found out that I needed to implement withLightColumnFilter and I upgraded to 0.5.3 willing to test this option.

It turns out that I'm struggling with this error (details at the end of this post), and I'm stucked with this right now so I ran out of options and came here after hours of googling some solution (I even ran into [this post](https://github.com/l-lin/angular-datatables/issues/58)).

My html looks pretty like this:

```
<table datatable="" dt-options="dt.options" dt-columns="dt.columns" dt-instance="dt.instance" class="table table-striped table-bordered dt-responsive">
      <tfoot><tr><th></th></tr></tfoot>
</table>
```

Aaand my controller looks pretty like this:

```
$scope.dt = {
      columns: [ ... ],
      instance: {},
      options: DTOptionsBuilder.newOptions()
        .withOption('ajax', {
          headers: {
            "...": "..."
          },
          url:"/api/some-uri",
          type: 'GET',
        }).withDataProp('data')
        .withBootstrap()
        .withOption('serverSide', true)
        .withOption('createdRow', OnRowCreated)
        .withPaginationType('full_numbers')
        .withOption('aaSorting',[0,'asc'])
        .withLightColumnFilter({
          0 : { "type" : "text"}
        })

    };
```

And the dependencies are presented this way:

```
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/datatables/media/js/jquery.dataTables.js"></script>
<script src="bower_components/angular-datatables/dist/angular-datatables.js"></script>
<script src="bower_components/angular-datatables/dist/plugins/light-columnfilter/angular-datatables.light-columnfilter.js"></script>
```

I would be pleased if any of you guys could send some light in the right approach.

The error is right below:
```
TypeError: DTLoadingTemplate.compileHtml is not a function
    at Object.showLoading (https://localhost:9000/bower_components/angular-datatables/dist/angular-datatables.js:713:58)
    at postLink (https://localhost:9000/bower_components/angular-datatables/dist/angular-datatables.js:50:31)
```

Thanks in advance.

**Comment by l-lin** [comment]
You must have overriden the `DTLoadingTemplate` factory. Now, you will need to initialize like this:
```js
angular.module('showcase', ['datatables'])
.run(initDT);

function initDT(DTDefaultOptions) {
    DTDefaultOptions.setLoadingTemplate('<img src="images/loading.gif" />');
}
```
See the [v0.5.2 release's note](https://github.com/l-lin/angular-datatables/releases/tag/v0.5.2).

**Comment by rjalvesp** [comment]
Hi @l-lin, I've tried that and worked, our crew was overriding the DTLoadingTemplate factory. I knew the solution was simple, thanks a lot for your time.
